package ro.tuc.pt.presentation;

import ro.tuc.pt.business_logic.ProductBLL;
import ro.tuc.pt.utils.TableFactory;

import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * The ProductController class implements ActionListener interface and its method actionPerformed is called
 * every time the user selects any of the operations insert, delete or update.
 * This class calls the ProductBLL class to perform the queries.
 */
public class ProductController implements ActionListener {
    private final ProductView productView;
    private final ProductBLL productBLL = new ProductBLL();
    public ProductController(ProductView productView) {
        this.productView = productView;
        updateTable();
    }

    /**
     * The actionPerformed overridden method calls the add, delete and update methods to execute the
     * queries on the tables of the database when the corresponding buttons have been pushed by the user.
     * @param e the action generated by the pressing of a button
     */
    @Override
    public void actionPerformed(ActionEvent e) {
        String command = e.getActionCommand();
        if(command.equals("add")){
           productBLL.add(productView.getIdText(), productView.getNameText(), productView.getPriceText(), productView.getStockText());
        } else if(command.equals("delete")){
            productBLL.delete(productView.getIdText());
        } else if(command.equals("update")){
            productBLL.update(productView.getIdText(), productView.getNameText(), productView.getPriceText(), productView.getStockText());
        }
        updateTable();
    }

    /**
     * After every query executed, the updateTable method regenerates the table for the gui to be updated
     */
    public void updateTable(){
        DefaultTableModel model = TableFactory.createTable(productBLL.findALl());
        productView.table.setModel(model);
    }
}
